### ISSUE TITLE
Convert Date strings to readable format

### ISSUE THREAD

**Issue by dastrong** [chingu-voyages/v13-bears-team-04#34]
Instead of showing a Date string in post and comments, we should render something like this:
> 2 days ago
> 3 hours ago
> a moment ago

These are used in posts and comments.

Here's an [article](https://blog.logrocket.com/4-alternatives-to-moment-js-for-internationalizing-dates/) with 4 alternatives to MomentJS (which is a really large package).

I'm not sure if any of the ones mentioned it in can convert to the examples above, but give it a read and try.

**Comment by Wonder2210** [comment]
hello , can i take this issue ?

**Comment by dastrong** [comment]
@Wonder2210 How did you find this? Did you join Chingu? Sorry, I just wasn't expecting other people to comment on this.

I'll have to discuss it with my team before letting you handle this.

I'll let you know either way.

**Comment by Wonder2210** [comment]
Haha i just was looking for some " good first issues" and i found this repo among those .
Ps:thanks to this repo i discover and joined chingu ✌
