### ISSUE TITLE
Update past components to use the new Button component

### ISSUE THREAD

**Issue by dastrong** [chingu-voyages/v13-bears-team-04#36]
Bueller? Bueller?

This has been visible for awhile now. 

Update your past components to reflect the changes made to `Button`.

Let me know if you have any issues or need assistance.

Please just add a message below, if you're the first one to complete your old components.

The second person to finish may close this issue.

**Comment by Saggitarie** [comment]
Just fixed the reusable button on Trending community

**Comment by dastrong** [comment]
#45 merged, so this is done.
