### ISSUE TITLE
Connect repo with now.sh deployment

### ISSUE THREAD

**Issue by dastrong** [chingu-voyages/v13-bears-team-04#38]
Benefits: for submitted PR, you can see a preview deploy

Cons: *I can't get it to connect with our repo!*

**Comment by dastrong** [comment]
@beboptank @Saggitarie 

Could either of you try making an account on [now](now.sh) and see if you can 'Install Now for GitHub' with our repo. 

It always tells me that I don't have organizational approval even though Jim has granted it for us.

**Comment by dastrong** [comment]
Awaiting email from Zeit Now support..

**Comment by dastrong** [comment]
@beboptank @Saggitarie 

Turns out we need a higher up from Chingu to create a project on now and add us or we'll need to move the project to a personal repo, so one of us can set it up and manage it.

Do either of you want some practice moving a repo and deploying it?

**Comment by beboptank** [comment]
I can do if @Saggitarie is okay with that. Good practice for me.

**Comment by Saggitarie** [comment]
No problem. Give it a go!

**Comment by dastrong** [comment]
Can't auto-deploy through this repo because it's through the Chingu organization and Zeit Now only allows one integration per organization.

We could fork it and we have tested it, but ultimately I want to keep the repo, in it's original place, so other Chingu's can view it.

I'll update the main readme with the final prod URL once it's all ready.
