### ISSUE TITLE
Bug: Styles not loaded on page change via Link

### ISSUE THREAD

**Issue by dastrong** [chingu-voyages/v13-bears-team-04#51]
If you navigate to another page through the NextJS Link component (which keeps the site from reloading), the styles on the second page won't be loaded.

This is a known issue with NextJS and the withSass plugin that we're using. 

Although there are some workarounds out there, we can live with this issue for the time-being.

NextJS has an experimental fix out and I have notifications on for when it becomes stable.

You can follow this issue and read about it [here](https://github.com/zeit/next.js/issues/8626)

**Note:** if the fix isn't stable by the time we're finished this project, we can implement a workaround or use the experimental flag.

**Comment by dastrong** [comment]
@beboptank @Saggitarie 

NextJS 9.2 solves this issue I believe. 

You can read about it [here](https://github.com/zeit/next.js/issues/8626#event-2955149652).

Looks like we might need to put all our`.scss` files inside the sass folder and import/export through the `main.scss` file like the 7-1 architecture mentioned.

Then we would import that sass file in `_app.js`.

Consequently, I believe we could remove all `.scss` imports at the components levels...?

Anyone want to handle this?

**Comment by Saggitarie** [comment]
@dastrong 
Okay, I'll take this issue.
